BEGIN;

CREATE TABLE IF NOT EXISTS sys_dict
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(64)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    value_type VARCHAR(16)  NOT NULL DEFAULT 'STRING',
    is_system  BOOLEAN      NOT NULL DEFAULT FALSE,
    status     BOOLEAN      NOT NULL DEFAULT TRUE,
    remark     VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_dict_code
        CHECK (code ~ '^[a-z][a-z0-9_.-]*$'),
    CONSTRAINT ck_sys_dict_value_type
        CHECK (value_type IN ('STRING', 'INTEGER', 'BOOLEAN'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_dict_code_lower
    ON sys_dict (LOWER(code));

CREATE TABLE IF NOT EXISTS sys_dict_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_id    BIGINT       NOT NULL,
    label      VARCHAR(100) NOT NULL,
    value      VARCHAR(100) NOT NULL,
    is_default BOOLEAN      NOT NULL DEFAULT FALSE,
    status     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    extra      JSONB        NOT NULL DEFAULT '{}'::JSONB,
    remark     VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_dict_item_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT fk_sys_dict_item_dict
        FOREIGN KEY (dict_id)
            REFERENCES sys_dict (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_sys_dict_item_value
        UNIQUE (dict_id, value)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_dict_item_default
    ON sys_dict_item (dict_id)
    WHERE is_default = TRUE;

CREATE INDEX IF NOT EXISTS idx_sys_dict_item_query
    ON sys_dict_item (dict_id, status, sort_order, id);

CREATE TABLE IF NOT EXISTS sys_menu
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT,
    name        VARCHAR(64)  NOT NULL,
    title       VARCHAR(100) NOT NULL,
    menu_type   SMALLINT     NOT NULL,
    path        VARCHAR(255) NOT NULL,
    component   VARCHAR(255),
    redirect    VARCHAR(255),
    icon        VARCHAR(100),
    hidden      BOOLEAN      NOT NULL DEFAULT FALSE,
    status      BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    description VARCHAR(255),
    remark      VARCHAR(500),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_menu_type
        CHECK (menu_type IN (1, 2)),
    CONSTRAINT ck_sys_menu_page_component
        CHECK (menu_type = 1 OR NULLIF(BTRIM(component), '') IS NOT NULL),
    CONSTRAINT ck_sys_menu_parent_self
        CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT ck_sys_menu_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT fk_sys_menu_parent
        FOREIGN KEY (parent_id)
            REFERENCES sys_menu (id)
            ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_menu_name
    ON sys_menu (name);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_menu_name_lower
    ON sys_menu (LOWER(name));

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_menu_path
    ON sys_menu (path);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_menu_path_lower
    ON sys_menu (LOWER(path));

CREATE INDEX IF NOT EXISTS idx_sys_menu_parent_status_sort
    ON sys_menu (parent_id, status, sort_order, id);

CREATE TABLE IF NOT EXISTS sys_organize
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  BIGINT,
    name       VARCHAR(100) NOT NULL,
    status     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    remark     VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_organization_parent
        FOREIGN KEY (parent_id)
            REFERENCES sys_organize (id)
            ON DELETE RESTRICT,
    CONSTRAINT uk_sys_organization_parent_name
        UNIQUE NULLS NOT DISTINCT (parent_id, name)
);

CREATE INDEX IF NOT EXISTS idx_sys_organization_parent_sort
    ON sys_organize (parent_id, sort_order);

CREATE TABLE IF NOT EXISTS sys_post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id     BIGINT       NOT NULL,
    code       VARCHAR(64)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    status     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    remark     VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sys_post_organization
        FOREIGN KEY (org_id)
            REFERENCES sys_organize (id)
            ON DELETE RESTRICT,
    CONSTRAINT uk_sys_post_org_code
        UNIQUE (org_id, code),
    CONSTRAINT uk_sys_post_org_name
        UNIQUE (org_id, name)
);

CREATE INDEX IF NOT EXISTS idx_sys_post_org_sort
    ON sys_post (org_id, sort_order);

CREATE TABLE IF NOT EXISTS sys_role
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64) NOT NULL,
    name            VARCHAR(64) NOT NULL,
    data_scope_type VARCHAR(32) NOT NULL DEFAULT 'CURRENT_ORG',
    built_in        BOOLEAN     NOT NULL DEFAULT FALSE,
    status          BOOLEAN     NOT NULL DEFAULT TRUE,
    sort_order      INTEGER     NOT NULL DEFAULT 0,
    remark          VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_role_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT ck_sys_role_data_scope_type
        CHECK (
            data_scope_type IN (
                                'ALL',
                                'CURRENT_ORG',
                                'CURRENT_ORG_AND_CHILDREN',
                                'CUSTOM_ORG'
                )
            ),
    CONSTRAINT uk_sys_role_code
        UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS sys_role_data_org
(
    role_id BIGINT NOT NULL,
    org_id  BIGINT NOT NULL,
    PRIMARY KEY (role_id, org_id),
    CONSTRAINT fk_sys_role_data_org_role
        FOREIGN KEY (role_id)
            REFERENCES sys_role (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_data_org_org
        FOREIGN KEY (org_id)
            REFERENCES sys_organize (id)
            ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_sys_role_data_org_org_id
    ON sys_role_data_org (org_id);

CREATE TABLE IF NOT EXISTS sys_resource
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id    BIGINT       NOT NULL,
    code       VARCHAR(128) NOT NULL,
    name       VARCHAR(64)  NOT NULL,
    status     BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order INTEGER      NOT NULL DEFAULT 0,
    remark     VARCHAR(500),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sys_resource_sort_order
        CHECK (sort_order >= 0),
    CONSTRAINT fk_sys_resource_menu
        FOREIGN KEY (menu_id)
            REFERENCES sys_menu (id)
            ON DELETE CASCADE,
    CONSTRAINT uk_sys_resource_code
        UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_sys_resource_menu_id
    ON sys_resource (menu_id);

CREATE TABLE IF NOT EXISTS sys_user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    org_id               BIGINT,
    account              VARCHAR(64)  NOT NULL,
    username             VARCHAR(64)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    avatar               VARCHAR(500),
    sex                  VARCHAR(16)  NOT NULL DEFAULT 'unknown',
    email                VARCHAR(254),
    mobile               VARCHAR(32),
    enabled              BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password BOOLEAN      NOT NULL DEFAULT TRUE,
    password_changed_at  TIMESTAMP,
    built_in             BOOLEAN      NOT NULL DEFAULT FALSE,
    remark               VARCHAR(500),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_sys_user PRIMARY KEY (id),
    CONSTRAINT ck_sys_user_sex
        CHECK (sex IN ('male', 'female', 'unknown')),
    CONSTRAINT fk_sys_user_org
        FOREIGN KEY (org_id)
            REFERENCES sys_organize (id)
            ON DELETE RESTRICT,
    CONSTRAINT uk_sys_user_account
        UNIQUE (account)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_email_lower
    ON sys_user (LOWER(email))
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_mobile
    ON sys_user (mobile)
    WHERE mobile IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_sys_user_org_id
    ON sys_user (org_id);

CREATE TABLE IF NOT EXISTS sys_role_menu
(
    role_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, menu_id),
    CONSTRAINT fk_sys_role_menu_role
        FOREIGN KEY (role_id)
            REFERENCES sys_role (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_menu_menu
        FOREIGN KEY (menu_id)
            REFERENCES sys_menu (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sys_role_menu_menu_id
    ON sys_role_menu (menu_id);

CREATE TABLE IF NOT EXISTS sys_role_resource
(
    role_id     BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, resource_id),
    CONSTRAINT fk_sys_role_resource_role
        FOREIGN KEY (role_id)
            REFERENCES sys_role (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sys_role_resource_resource
        FOREIGN KEY (resource_id)
            REFERENCES sys_resource (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sys_role_resource_resource_id
    ON sys_role_resource (resource_id);

CREATE TABLE IF NOT EXISTS sys_user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_sys_user_role_user
        FOREIGN KEY (user_id)
            REFERENCES sys_user (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES sys_role (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sys_user_role_role_id
    ON sys_user_role (role_id);

CREATE TABLE IF NOT EXISTS sys_user_post
(
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, post_id),
    CONSTRAINT fk_sys_user_post_user
        FOREIGN KEY (user_id)
            REFERENCES sys_user (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_sys_user_post_post
        FOREIGN KEY (post_id)
            REFERENCES sys_post (id)
            ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sys_user_post_post_id
    ON sys_user_post (post_id);

COMMIT;
